
slurm:

    run_configs:
        - 'scan1'

    configs: {

        'scan1': {
            'exe': ['mpi-numpy.py'],
            'memory': [ 100, 200, 500, 1000 ],
#            'memory': [100, 200],
            'gzip': [0],
            'chunk': [0],
            'wpn': [ 1, 2, 5, 10],
#            'wpn': [1],
            'nodes': [ 1, 2],
#            'nodes': [1],
            'mpi': ['mvapich2'],
            'omp': [1],
#            'cores_per_cpu': [20],
            'partition': ['photon'],
            'time': [60],
            'repeats': [1],
            'combinations': ['cross'] # or unique
        }
    }
